ARG DISTRIB=ubuntu
ARG RELEASE=focal

FROM ${DISTRIB}:${RELEASE}

ARG DISTRIB
ARG RELEASE
ARG NGINX_VERSION=1.26.0
ARG NGINX_DEB_RELEASE=1
ARG BROTLI_VERSION=1.1.0

ENV DEBIAN_FRONTEND="noninteractive"

RUN apt-get update && apt-get --no-install-recommends --no-install-suggests -y install \
    cmake git wget ca-certificates curl openssl gnupg2 apt-transport-https \
    unzip make libpcre3-dev zlib1g-dev build-essential devscripts \
    debhelper quilt lsb-release libssl-dev lintian uuid-dev

WORKDIR /root

RUN echo "*** Building ngx_brotli ${BROTLI_VERSION} against ${NGINX_VERSION}-${NGINX_DEB_RELEASE}~${RELEASE} ***"

RUN git clone https://github.com/google/ngx_brotli.git && cd ngx_brotli && git submodule update --init --recursive
RUN wget -qO - https://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz | tar zxvf -

COPY debian nginx-${NGINX_VERSION}/debian
RUN sed -i "s/{NGINX_VERSION}/${NGINX_VERSION}-${NGINX_DEB_RELEASE}~${RELEASE}/g" nginx-${NGINX_VERSION}/debian/control

RUN mkdir ngx_brotli/deps/brotli/out
WORKDIR /root/ngx_brotli/deps/brotli/out
RUN cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_SHARED_LIBS=OFF \
    -DCMAKE_C_FLAGS="-Ofast -m64 -march=native -mtune=native -flto -funroll-loops -ffunction-sections -fdata-sections -Wl,--gc-sections" \
    -DCMAKE_CXX_FLAGS="-Ofast -m64 -march=native -mtune=native -flto -funroll-loops -ffunction-sections -fdata-sections -Wl,--gc-sections" \
    -DCMAKE_INSTALL_PREFIX=./installed .. && \
    cmake --build . --config Release --target brotlienc

WORKDIR /root/nginx-${NGINX_VERSION}
RUN dch -v ${BROTLI_VERSION}+${NGINX_VERSION}-${NGINX_DEB_RELEASE}~${RELEASE} "Build for brotli ${BROTLI_VERSION} against nginx ${NGINX_VERSION}"
RUN dpkg-buildpackage

WORKDIR /root

RUN mkdir /src && mv libnginx-mod-brotli* /src/ && cp nginx-${NGINX_VERSION}/debian/changelog /src/
RUN dpkg -c /src/libnginx-mod-brotli_*.deb

RUN curl -L https://nginx.org/keys/nginx_signing.key | apt-key add -
RUN echo "deb https://nginx.org/packages/${DISTRIB}/ ${RELEASE} nginx" >> /etc/apt/sources.list.d/nginx.list

RUN apt-get update && apt-get -V --no-install-recommends --no-install-suggests -y install nginx=${NGINX_VERSION}-${NGINX_DEB_RELEASE}~${RELEASE}

RUN dpkg -i /src/libnginx-mod-brotli_*.deb && \
    sed -i '1iload_module modules/ngx_http_brotli_filter_module.so;' /etc/nginx/nginx.conf && \
    sed -i '1 abrotli on;' /etc/nginx/conf.d/default.conf && \
    nginx -t && /etc/init.d/nginx start && echo "Testing NGiNX headers for Brotli presence : " && \
    curl -s -I -H 'Accept-Encoding: br,gzip,deflate' http://localhost/ |grep 'Content-Encoding: br'

RUN dpkg -r libnginx-mod-brotli
RUN dpkg -P libnginx-mod-brotli
